let planeType = [
    {
        name:'歼10-A',
        generation:'三代',//代数，三代机、2代机、等等。
        seat:'单座',//单座、双座等等等。
    },
    {
        name:'歼11-A',
        generation:'三代',//代数，三代机、2代机、等等。
        seat:'双座',//单座、双座等等等。
    },
    {
        name:'歼12-A',
        generation:'三代',//代数，三代机、2代机、等等。
        seat:'单座',//单座、双座等等等。
    },
    {
        name:'歼13-A',
        generation:'三代',//代数，三代机、2代机、等等。
        seat:'双座',//单座、双座等等等。
    },
    {
        name:'歼14-A',
        generation:'三代',//代数，三代机、2代机、等等。
        seat:'单座',//单座、双座等等等。
    },
    {
        name:'歼15-A',
        generation:'三代',//代数，三代机、2代机、等等。
        seat:'双座',//单座、双座等等等。
    },
    {
        name:'歼16-A',
        generation:'三代',//代数，三代机、2代机、等等。
        seat:'单座',//单座、双座等等等。
    },
    {
        name:'歼17-A',
        generation:'四代',//代数，三代机、2代机、等等。
        seat:'双座',//单座、双座等等等。
    },
    {
        name:'歼18-A',
        generation:'四代',//代数，三代机、2代机、等等。
        seat:'单座',//单座、双座等等等。
    },
    {
        name:'歼19-A',
        generation:'四代',//代数，三代机、2代机、等等。
        seat:'双座',//单座、双座等等等。
    },{
        name:'歼20-A',
        generation:'四代',//代数，三代机、2代机、等等。
        seat:'单座',//单座、双座等等等。
    },
    {
        name:'歼10-A',
        generation:'四代',//代数，三代机、2代机、等等。
        seat:'双座',//单座、双座等等等。
    },

    {
        name:'歼21-A',
        generation:'四代',//代数，三代机、2代机、等等。
        seat:'单座',//单座、双座等等等。
    },
    {
        name:'歼22-A',
        generation:'三代',//代数，三代机、2代机、等等。
        seat:'双座',//单座、双座等等等。
    },
    {
        name:'歼23-A',
        generation:'四代',//代数，三代机、2代机、等等。
        seat:'单座',//单座、双座等等等。
    },
];

for(let i =0;i < 136;i++){
    let tmp = i+24;
    planeType.push({
        name:'歼'+tmp+'-A',
        generation:'二代',
        seat:'双座'
    })
}
for(let i =0;i < 150;i++){
    planeType[i].id = i;
}
export {planeType}