let resdata = [
    {
        year:'2017',
        xItem:{
            name:'编号',
            value:['901']
        },
        yItem:{
            name:'剩余寿命',
            value:[200],
        },
        cross:'0.4'
    },
    {
        year:'2018',
        xItem:{
            name:'编号',
            value:['901']
        },
        yItem:{
            name:'剩余寿命',
            value:[200],
        },
        cross:'0.4'
    },
    {
        year:'2019',
        xItem:{
            name:'编号',
            value:['901']
        },
        yItem:{
            name:'剩余寿命',
            value:[200],
        },
        cross:'0.4'
    },
    {
        year:'2020',
        xItem:{
            name:'编号',
            value:['901']
        },
        yItem:{
            name:'剩余寿命',
            value:[200],
        },
        cross:'0.4'
    }
]

resdata.forEach(function(element){
    for(let i =0;i < 16;i ++){
        
    }
})

let resdata3 = {
    gross:0.4,
    2017:{
        xItem:{
            name:'机号',
            value:['901','902'],
        },
        yItem:{
            name:'余寿',
            value:[500,600],
        }
    },
    2018:{
        xItem:{
            name:'机号',
            value:['901','902'],
        },
        yItem:{
            name:'余寿',
            value:[500,600],
        }
    },
    2019:{
        xItem:{
            name:'机号',
            value:['901','902'],
        },
        yItem:{
            name:'余寿',
            value:[500,600],
        }
    },
    2020:{
        xItem:{
            name:'机号',
            value:['901','902'],
        },
        yItem:{
            name:'余寿',
            value:[500,600],
        }
    },
}


export {resdata}